# ===================================================================
# Master Keyword List for Property Furnishing Status
# Compiled and de-duplicated from Claude, ChatGPT, and Grok outputs.
# ===================================================================

# Keywords that strongly indicate a property is UNFURNISHED.
# The presence of any of these should flag the property as unfurnished.
negative_keywords:
  
  # Category 1: Direct statements of being unfurnished.
  direct_negations:
    - "apartment is unfurnished"
    - "bare property"
    - "comes unfurnished"
    - "comes without furniture"
    - "does not come furnished"
    - "empty of furniture"
    - "furniture not included"
    - "furniture not provided"
    - "furnishings not included"
    - "furnishings not provided"
    - "house is unfurnished"
    - "no furniture"
    - "no furniture included"
    - "no furniture provided"
    - "no furnishings"
    - "no furnishings provided"
    - "non-furnished"
    - "not furnished"
    - "not including furniture"
    - "not supplied furnished"
    - "not supplied with furniture"
    - "property is unfurnished"
    - "rental is unfurnished"
    - "un-furnished"
    - "unfurnished"
    - "unfurnished apartment"
    - "unfurnished house"
    - "unfurnished property"
    - "unfurnished rental"
    - "unfurnished unit"
    - "unit is unfurnished"
    - "without furniture"
    - "without furnishings"

  # Category 2: Phrases indicating the tenant is responsible for furniture.
  tenant_responsibility:
    - "bring your own furniture"
    - "byo furniture"
    - "furniture to be arranged by tenant"
    - "furniture to be provided by tenant"
    - "furniture to be supplied by tenant"
    - "own furniture required"
    - "provide your own furnishings"
    - "supply your own furniture"
    - "supply your own furnishings"
    - "tenant must furnish"
    - "tenant must provide furniture"
    - "tenant must provide furnishings"
    - "tenant must provide own furniture"
    - "tenant provides furniture"
    - "tenant provides furnishings"
    - "tenant responsible for furniture"
    - "tenant responsible for furnishing"
    - "tenant supplies all furniture"
    - "tenant to bring furniture"
    - "tenant to furnish"
    - "tenant to provide all furniture"
    - "tenant to provide own furniture"
    - "tenant to supply furniture"
    - "tenant to supply furnishings"
    - "tenant to supply own furniture"
    - "you provide furniture"
    - "you provide furnishings"
    - "you must furnish"

  # Category 3: Descriptions of the property's empty state.
  property_status_description:
    - "bare premises"
    - "bare unit"
    - "bare walls"
    - "completely empty"
    - "delivered empty"
    - "empty apartment"
    - "empty house"
    - "empty possession"
    - "empty shell"
    - "empty unit"
    - "leased as a shell"
    - "leased empty"
    - "no fixtures or furniture"
    - "no furnishings"
    - "no furniture or fittings"
    - "no whitegoods or furniture"
    - "offered empty"
    - "premises cleared"
    - "premises empty"
    - "property cleared"
    - "property comes empty"
    - "property is bare"
    - "property is empty"
    - "property vacant"
    - "shell condition"
    - "totally empty"
    - "unfurnished and empty"
    - "vacant and unfurnished"
    - "vacant possession"

  # Category 4: Disclaimers for staged/photographed furniture.
  staging_display_disclaimers:
    - "decor for photos only"
    - "decoration for photos only"
    - "display furniture not included"
    - "display furniture not part of lease"
    - "display furniture only"
    - "display furnishings not included"
    - "display items not included"
    - "display purposes only"
    - "displayed furniture not included"
    - "furniture for display"
    - "furniture for display purposes only"
    - "furniture for illustration only"
    - "furniture for marketing purposes only"
    - "furniture for photographic purposes only"
    - "furniture for styling"
    - "furniture for styling purposes only"
    - "furniture in photos not included"
    - "furniture in pictures for display only"
    - "furniture not included in lease"
    - "furniture not part of lease"
    - "furniture not part of rental"
    - "furniture shown for display purposes"
    - "furniture shown for marketing purposes"
    - "furniture shown for presentation purposes"
    - "furniture shown for styling purposes"
    - "furniture shown is not included"
    - "furniture shown not included"
    - "furniture staged for photos"
    - "furnishings for display only"
    - "furnishings for styling only"
    - "furnishings not part of lease"
    - "furnishings shown for display"
    - "home styled for photography"
    - "images are for illustration only, property is unfurnished"
    - "images for illustrative purposes, unfurnished rental"
    - "marketing furniture only"
    - "photographic styling only"
    - "photos are indicative only and property is unfurnished"
    - "photos depict staged property, unfurnished in reality"
    - "photos for marketing purposes only"
    - "photos show styling furniture"
    - "presentation furniture only"
    - "property is not furnished, photos are for illustration"
    - "property is unfurnished, furniture in photos not included"
    - "property photographed furnished but rented unfurnished"
    - "property styled for photos only"
    - "property will be leased unfurnished"
    - "shown furniture not included"
    - "staged for photography only"
    - "staged for photos only"
    - "staged for photos, property unfurnished"
    - "staging furniture only"
    - "staging furniture will be removed"
    - "staging not included"
    - "styled for photos only"
    - "styled for presentation only"
    - "styling furniture not included"
    - "styling not included"
    - "styling purposes only"
    - "virtual staging"

  # Category 5: Informal or colloquial terms for unfurnished.
  informal_colloquial_terms:
    - "bare apartment"
    - "bare bones"
    - "bare bones rental"
    - "bare unit"
    - "blank canvas"
    - "bring your own stuff"
    - "clean slate"
    - "empty flat"
    - "empty slate"
    - "furniture free"
    - "furnishing free"
    - "just the basics no furniture"
    - "minus furniture"
    - "minus furnishings"
    - "no appliances or furniture"
    - "no inclusions"
    - "no whitegoods"
    - "nothing included"
    - "shell only"
    - "stripped bare"

  # Category 6: Explicit exclusion of furniture and other items.
  exclusion_of_items:
    - "absolutely no furniture"
    - "absolutely no furnishings"
    - "does not include any furniture"
    - "does not include any furniture or whitegoods"
    - "does not include any furnishings"
    - "excludes all furniture"
    - "excludes all furniture and appliances"
    - "excludes all furnishings"
    - "excludes all furnishings and equipment"
    - "no appliances or furniture included"
    - "no bed, sofa or table provided"
    - "no essential furniture included"
    - "no furniture of any kind"
    - "no furniture or appliances"
    - "no furniture or whitegoods"
    - "no furnishings of any kind"
    - "no furnishings or appliances"
    - "no furnishings or whitegoods"
    - "no furnishings whatsoever"
    - "no furniture whatsoever"
    - "no major furniture items included"
    - "zero furniture included"
    - "zero furnishings included"

# ===================================================================

# Keywords that strongly indicate a property is FURNISHED.
# The presence of these can be used to flag a property as furnished.
positive_keywords:

  # Category 1: Direct statements of being furnished.
  direct_affirmations:
    - "all furniture included"
    - "comes furnished"
    - "comes with furniture"
    - "furnished"
    - "fully equipped with furniture"
    - "fully furnished"
    - "furnishings included"
    - "includes furniture"
    - "leased as furnished"
    - "leased furnished"
    - "move-in ready with furniture"
    - "offered furnished"
    - "property is furnished"
    - "provided furnished"
    - "supplied with furniture"
    - "well-furnished"
  
  # Category 2: Phrases promoting the convenience of a furnished property.
  promotional_phrases:
    - "bring only your personal belongings"
    - "just bring your suitcase"
    - "move straight in"
    - "ready to move in"
    - "simply move in"
    - "suitcase-ready"
    - "turnkey property"

  # Category 3: Phrases describing the specific furniture included.
  description_of_inclusions:
    - "bed, sofa and table included"
    - "comes with fridge and washing machine"
    - "fitted with appliances and furniture"
    - "furniture package included"
    - "furniture provided"
    - "includes all essential furniture"
    - "includes bed and sofa"
    - "includes whitegoods"
    - "major furniture included"
    - "with all appliances and furniture"
    - "with all furniture"
    - "with all furnishings"
    - "with beds, couch, and dining table"
    - "with complete furnishings"
    - "with whitegoods and furniture"

# ===================================================================

# Keywords indicating that the furnishing status is OPTIONAL or FLEXIBLE.
# These are crucial for identifying complex cases where the tenant has a choice.
# The presence of these should flag the property as 'Optional'.
optional_keywords:

  # Category 1: Direct statements of choice
  direct_choice_statements:
    - "can be furnished or unfurnished"
    - "furnished or unfurnished"
    - "can come furnished or unfurnished"
    - "offered as furnished or unfurnished"
    - "available furnished or unfurnished"
    - "option for furnished or unfurnished"
    - "your choice!"
    - "flexible with furniture"
    - "furniture negotiable"
    - "can be leased, furnished or unfurnished"
    - "can be provided furnished or unfurnished"
    - "can come with the furniture as displayed or unfurnished"
    - "and it can be fully furnished, partly furnished or unfurnished"

  # Category 2: Conditional provisions (upon request, etc.)
  conditional_provisions:
    - "can be included upon request"
    - "furniture can be provided upon request"
    - "fridge and washing machine can be included"
    - "owner is happy to provide"
    - "can provide fridge & washing machine"
    - "can be provided at an additional cost"
    - "subject to a higher rent"
    - "contact us to enquire about the inclusion"

  # Category 3: Statements about removing existing furniture
  removal_of_furniture:
    - "can be removed should you have your own"
    - "happy to remove if you have your own"
    - "willing to remove furniture if requested"
    - "but can be removed if you have your own"
    - "currently furnished, can be unfurnished if required"
    - "but is flexible to be unfurnished"

  # Category 4: Partial or mixed furnishing states
  partial_or_mixed_states:
    - "partly furnished"
    - "part furnished"
    - "partially furnished"
    - "can come partly furnished"
    - "semi-furnished"
    - "with or without the furniture"
    - "as new furniture & home appliances"
    - "complete with high-end furniture and appliances"
    - "complete with stylish furniture"
