# 完整模式配置 (Full Mode)
# 运行: python run.py --mode full (或 python run.py)

# --- 基本设置 ---
url_file_path: 'config/url.txt'
features_config_path: 'config/features_config.yaml'
output_dir: 'output'

# --- 爬虫行为 ---
max_pages_per_search: 10
delay_between_pages: 3
delay_between_requests: 2

# --- 性能设置 ---
performance:
  requests_per_second: 1.5 # 每秒请求数

# --- 网络设置 ---
network:
  max_retries: 3
  backoff_factor: 0.5
  retry_statuses: [500, 502, 503, 504]
  timeout: 20

# --- 请求头 ---
headers:
  User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

# --- 输出设置 ---
# Excel写入缓冲区大小
buffer_size: 50
