# 简约模式配置 (Minimal Mode for Canva)
# 运行: python run.py --mode minimal

# --- 基本设置 ---
url_file_path: 'config/url.txt'
features_config_path: 'config/features_config.yaml'
output_dir: 'output'

# --- 爬虫行为 ---
max_pages_per_search: 5
delay_between_pages: 2
delay_between_requests: 1

# --- 性能设置 ---
performance:
  requests_per_second: 1.5 # 每秒请求数

# --- 网络设置 ---
network:
  max_retries: 3
  backoff_factor: 0.5
  retry_statuses: [500, 502, 503, 504]
  timeout: 20

# --- 请求头 ---
headers:
  User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

# --- 输出设置 ---
buffer_size: 50

# --- 简约模式核心配置 ---
# 定义在简约模式下需要输出的列
minimal_columns:
  - "Title"
  - "Price"
  - "Address"
  - "URL"
  - "Cover Image URL"
  - "Description"
  - "Bedrooms"
  - "Bathrooms"
  - "Parking"
